---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - pachage-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
