name: Publish to PyPI
on:
  push:
    branches:
      - github-actions-tutorial
    tags:
      - "*.*.*"

jobs:
  build:
  if: github.ref =~ /^refs\/tags\/\d+\.\d+\.\d+$/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[build]
      
      - name: Build dist files
        run: python -m build
