name: Lint python code

on:
    pull_request:
        branches: 
            - github-actions-tutorial
    push:
        branches: 
            - github-actions-tutorial
    # This is used to restart the workflow in case of internal errors such as expired API keys
    workflow_dispatch: 

jobs:
    lint: # Name of the job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.9"
                cache: "pip"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install ruff

            - name: Run ruff
              run: ruff check --output-format=github

